# Generated by Django 6.0.3 on 2026-03-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='True if the student has finished the lesson content.')),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='The exact timestamp when the lesson was first marked complete.')),
                ('lesson', models.ForeignKey(help_text='The specific lesson being completed.', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.lesson')),
                ('user', models.ForeignKey(help_text='The student whose progress is being tracked.', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lesson Progresses',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
